import type { Metadata } from "next"
import { Figtree } from "next/font/google"
import "./globals.css"
import { Header } from "@/components/header/header"

const figtree = Figtree({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${figtree.className}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
